// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Competitions            string
	CompetitionsStages      string
	ExternalEntities        string
	FixturePredictions      string
	Fixtures                string
	GroupCompetitions       string
	Groups                  string
	RoleTypes               string
	StagePredictions        string
	Stages                  string
	Teams                   string
	TeamsCompetitions       string
	TeamsCompetitionsStages string
	Users                   string
	UsersInGroups           string
	Vendors                 string
}{
	Competitions:            "competitions",
	CompetitionsStages:      "competitions_stages",
	ExternalEntities:        "external_entities",
	FixturePredictions:      "fixture_predictions",
	Fixtures:                "fixtures",
	GroupCompetitions:       "group_competitions",
	Groups:                  "groups",
	RoleTypes:               "role_types",
	StagePredictions:        "stage_predictions",
	Stages:                  "stages",
	Teams:                   "teams",
	TeamsCompetitions:       "teams_competitions",
	TeamsCompetitionsStages: "teams_competitions_stages",
	Users:                   "users",
	UsersInGroups:           "users_in_groups",
	Vendors:                 "vendors",
}
